//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace weather.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Geoinfo
    {
        public Geoinfo()
        {
            this.Forecasts = new HashSet<Forecast>();
        }
    
        public int GeoinfoId { get; set; }
        public Nullable<System.DateTime> NextUpdate { get; set; }
        public string Country { get; set; }
        public string Region { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public string City { get; set; }
    
        public virtual ICollection<Forecast> Forecasts { get; set; }
    }
}
